# [connections.mydb]
# dialect = "mysql"
# url = "mysqldb://root:@127.0.0.1:3306/diabetes"


[connections.mydb]
type = "mysql"
dialect = "mysql"
host = "ql12.freesqldatabase.com"
driver = "pymysql"
port = 3306
database = "sql12648119"
username = "sql12648119"
password = "8NcUliQmDz"

